name: check lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Gradle check lint command
        uses: Raul6469/android-gradle-action@2.0.0
        with:
          script: lintKotlin